language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - coverage run pytest --source=/home/travis/build/ivanmillan36/MegaChess/ --omit main.py,player.py -m pytest
after_success:
  - coveralls