language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=/home/ivanmillan36/Documentos/proyectos_VSCode/MegaChess2 tests.py
after_success:
  - coveralls