language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - coverage run pytest --source=/home/travis/build/ivanmillan36/MegaChess/ -m pytest
after_success:
  - coveralls